### ISSUE TITLE
Constantly getting vtsls: -32603: Request textDocument/inlayHint failed with message

### ISSUE THREAD

**Issue by ecosse3** [yioneko/nvim-vtsls#12]
Hi,

**is there a way to automatically select _workspace_ typescript server version instead using VSCode one by default?**

I'm constantly getting error:
![image](https://github.com/user-attachments/assets/338adf36-555c-4f2c-abf1-6cb08f1f9ca7)
```
Error  12:13:49 notify.error vtsls: -32603: Request textDocument/inlayHint failed with message: <semantic> TypeScript Server Error (5.6.2)
No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:182367:11)
    at ScriptInfo.getDefaultProject (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:183066:23)
    at _ProjectService.doEnsureDefaultProjectForFile (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:186478:36)
    at _ProjectService.ensureDefaultProjectForFile (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:186473:103)
    at IpcIOSession.getFileAndProjectWorker (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:191723:77)
    at IpcIOSession.getFileAndProject (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:191709:17)
    at IpcIOSession.provideInlayHints (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:191471:36)
    at provideInlayHints (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:190566:43)
    at /Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:192655:15
    at IpcIOSession.executeWithRequestId (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:192644:14)
    at IpcIOSession.executeCommand (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:192653:29)
    at IpcIOSession.onMessage (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js:192701:68)
    at process.<anonymous> (/Users/lukasz.kurpiewski/.local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/tsserver.js:525:14)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

When I switch to workspace typescript the error is gone and `vtsls` is working great.

**Comment by yioneko** [comment]
Yes, you can set `{ settings = { vtsls = { autoUseWorkspaceTsdk = true } } }` in your lsp server config. https://github.com/yioneko/vtsls#typescript-version

**Comment by ecosse3** [comment]
Thank you. Somehow missed this. Works great!
